baseURL = 'https://rly0nheart.com/'
languageCode = 'en-GB'
title = "Ritchie Mwewa"

[[module.imports]]
    path = "github.com/KKKZOZ/hugo-admonitions"

[params]
  brandIconFile = "logo.png"
  subtitle = "Bipedal Software Engineer from the Milky Way"
  dateFmt = "2 January 2006"
  author = "Ritchie Mwewa"
  description = "Ritchie Mwewa"

  [[params.social]]
    name = "Gravatar"
    url = "https://gravatar.com/rly0nheart"
  [[params.social]]
    name = "Bluesky"
    url = "https://bsky.app/profile/rly0nheart.com"
  [[params.social]]
    name = "LinkedIn"
    url = "https://linkedin.com/in/rly0nheart"
  [[params.social]]
    name = "Codeberg"
    url = "https://codeberg.org/rly0nheart"
  [[params.social]]
    name = "GitHub"
    url = "https://github.com/rly0nheart"
  [[params.social]]
    name = "Email"
    url = "mailto:hi@rly0nheart.com"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 2
  [[menu.main]]
    name = "Posts"
    url = "/posts"
    weight = 3
  [[menu.main]]
    name = "RSS"
    url = "/index.xml"
    weight = 8
  [[menu.main]]
    name = "Projects"
    url = "/projects"
    weight = 5
  [[menu.main]]
    name = "Tags"
    url = "/tags"
    weight = 6
  [[menu.main]]
    name = "Categories"
    url = "/categories"
    weight = 7
