baseURL = 'https://rly0nheart.com/'
languageCode = 'en-GB'
title = "Ritchie Mwewa"
theme = ['smigle']
[[module.mounts]]
source = 'static'
target = 'static'

[[module.mounts]]
source = 'images'
target = 'static/images'

[[module.imports]]
    path = "github.com/KKKZOZ/hugo-admonitions"

[params]
  brandIconFile = "logo.png"
  subtitle = "Bipedal Software Engineer from the Milky Way"
  dateFmt = "2 January 2006"
  author = "Ritchie Mwewa"
  enableRobotsTXT = true
  enableSitemap = true
  description = "Ritchie Mwewa"

  [[params.social]]
    name = "Gravatar"
    pre = '<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" style="margin-right: 0.2em; vertical-align: -0.125em;"><title>Gravatar</title><path d="M12 0c-1.326 0-2.4 1.074-2.4 2.4v8.4c0 1.324 1.074 2.398 2.4 2.398s2.4-1.074 2.4-2.398V5.21c2.795.99 4.799 3.654 4.799 6.789 0 3.975-3.225 7.199-7.199 7.199S4.801 15.975 4.801 12c0-1.989.805-3.789 2.108-5.091.938-.938.938-2.458 0-3.396s-2.458-.938-3.396 0C1.344 5.686 0 8.686 0 12c0 6.627 5.373 12 12 12s12-5.373 12-12S18.627 0 12 0"/></svg>'
    url = "https://gravatar.com/rly0nheart"
  [[params.social]]
    name = "Bluesky"
    pre = '<i class="fa-brands fa-bluesky"></i>'
    url = "https://bsky.app/profile/rly0nheart.com"
  [[params.social]]
    name = "Mastodon"
    pre = '<i class="fa-brands fa-mastodon"></i>'
    url = "https://infosec.exchange/@rly0nheart"
  [[params.social]]
    name = "LinkedIn"
    pre = '<i class="fa-brands fa-linkedin"></i>'
    url = "https://linkedin.com/in/rly0nheart"
  [[params.social]]
    name = "Codeberg"
    pre = '<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" style="margin-right: 0.2em; vertical-align: -0.125em;"><title>Codeberg</title><path d="M11.999.747A11.974 11.974 0 0 0 0 12.75c0 2.254.635 4.465 1.833 6.376L11.837 6.19c.072-.092.251-.092.323 0l4.178 5.402h-2.992l.065.239h3.113l.882 1.138h-3.674l.103.374h3.86l.777 1.003h-4.358l.135.483h4.593l.695.894h-5.038l.165.589h5.326l.609.785h-5.717l.182.65h6.038l.562.727h-6.397l.183.65h6.717A12.003 12.003 0 0 0 24 12.75 11.977 11.977 0 0 0 11.999.747zm3.654 19.104.182.65h5.326c.173-.204.353-.433.513-.65zm.385 1.377.18.65h3.563c.233-.198.485-.428.712-.65zm.383 1.377.182.648h1.203c.356-.204.685-.412 1.042-.648zz"/></svg>'
    url = "https://codeberg.org/rly0nheart"
  [[params.social]]
    name = "GitHub"
    pre = '<i class="fa-brands fa-github"></i>'
    url = "https://github.com/rly0nheart"
  [[params.social]]
    name = "Email"
    pre = '<i class="fa-solid fa-envelope"></i>'
    url = "mailto:hi@rly0nheart.com"

[menu]
  [[menu.main]]
    name = "Home"
    pre = '<i class="fa-solid fa-home"></i>'
    url = "/"
    weight = 1
  [[menu.main]]
    name = "About"
    pre = '<i class="fa-solid fa-user"></i>'
    url = "/about"
    weight = 2
  [[menu.main]]
    name = "Posts"
    pre = '<i class="fa-solid fa-book"></i>'
    url = "/posts"
    weight = 3
  [[menu.main]]
    name = "Feed"
    pre = '<i class="fa-solid fa-rss"></i>'
    url = "/index.xml"
    weight = 4
  [[menu.main]]
    name = "Projects"
    pre = '<i class="fa-solid fa-code"></i>'
    url = "/projects"
    weight = 5
  [[menu.main]]
    name = "Tags"
    pre = '<i class="fa-solid fa-tags"></i>'
    url = "/tags"
    weight = 6
  [[menu.main]]
    name = "Categories"
    pre = '<i class="fa-solid fa-layer-group"></i>'
    url = "/categories"
    weight = 7