baseURL = 'https://rly0nheart.com/'
languageCode = 'en-GB'
title = "Ritchie Mwewa"
theme = 'smigle'

[params]
  brandIconFile = "logo.png"
  subtitle = "Bipedal Software Engineer from the Milky Way"
  dateFmt = "2 January 2006"
  author = "Ritchie Mwewa"
  enableRobotsTXT = true
  enableSitemap = true
  description = "Ritchie Mwewa"
  
  [[params.social]]
    logo = "git"
    name = "Codeberg"
    url = "https://codeberg.org/rly0nheart"

  [[params.social]]
    logo = "github"
    name = "GitHub"
    url = "https://github.com/rly0nheart"

  [[params.social]]
    name = "Bluesky"
    url = "https://bsky.app/profile/rly0nheart.com"
  
  [[params.social]]
    name = "LinkedIn"
    url = "https://linkedin.com/in/rly0nheart"
  
  [[params.social]]
    name = "Email"
    url = "mailto:hi@rly0nheart.com"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2

  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 3

  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 4
    
  [[menu.main]]
    name = "RSS"
    url = "/index.xml/"
    weight = 5

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 6

  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 7
